import { useEffect, useState, type ReactNode } from "react";
import { BellRing, Building2, Check, ChevronRight, Cloud, Code2, KeyRound, Plus, RefreshCw, ShieldCheck, SlidersHorizontal } from "lucide-react";

type Tab = "general" | "notifications" | "security" | "integrations";
type Preferences = { organization: string; currency: string; timezone: string; dateFormat: string; emailNotifications: boolean; systemAlerts: boolean; maintenanceReminders: boolean; weeklyReports: boolean; documentAlerts: boolean; twoFactor: boolean; passwordLength: string; autoLogout: string };
const defaults: Preferences = { organization: "Sterling Assurance PLC", currency: "NGN (₦)", timezone: "(UTC+01:00) West Central Africa", dateFormat: "DD/MM/YYYY", emailNotifications: true, systemAlerts: true, maintenanceReminders: true, weeklyReports: false, documentAlerts: true, twoFactor: true, passwordLength: "12 Characters", autoLogout: "30" };
const tabs: { id: Tab; label: string; icon: typeof Building2 }[] = [{ id: "general", label: "General settings", icon: Building2 }, { id: "notifications", label: "Notifications", icon: BellRing }, { id: "security", label: "Security & access", icon: ShieldCheck }, { id: "integrations", label: "Integrations", icon: Code2 }];
const inputClass = "h-10 w-full rounded-md border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition focus:border-[#1e3a8a] focus:ring-2 focus:ring-[#1e3a8a]/10";

const Toggle = ({ checked, onChange }: { checked: boolean; onChange: () => void }) => <button aria-checked={checked} className={`relative h-6 w-11 rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-[#1e3a8a]/30 ${checked ? "bg-[#1e3a8a]" : "bg-slate-300"}`} onClick={onChange} role="switch" type="button"><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${checked ? "translate-x-6" : "translate-x-1"}`} /></button>;
const Field = ({ label, children }: { label: string; children: ReactNode }) => <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>;

export default function Settings() {
  const [tab, setTab] = useState<Tab>("general");
  const [settings, setSettings] = useState<Preferences>(defaults);
  const [saved, setSaved] = useState(false);
  useEffect(() => { try { const stored = localStorage.getItem("alms-settings"); if (stored) setSettings({ ...defaults, ...JSON.parse(stored) }); } catch { localStorage.removeItem("alms-settings"); } }, []);
  const update = <K extends keyof Preferences>(key: K, value: Preferences[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { localStorage.setItem("alms-settings", JSON.stringify(settings)); setSaved(true); window.setTimeout(() => setSaved(false), 2500); };
  const notification = (title: string, description: string, key: keyof Preferences) => <div className="flex items-center justify-between gap-5 rounded-lg border border-slate-200 bg-white p-4" key={key}><div><p className="text-sm font-semibold text-slate-900">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div><div className="flex shrink-0 items-center gap-3"><span className={`hidden text-[11px] font-bold tracking-wide sm:block ${settings[key] ? "text-[#1e3a8a]" : "text-slate-400"}`}>{settings[key] ? "ACTIVE" : "INACTIVE"}</span><Toggle checked={Boolean(settings[key])} onChange={() => update(key, !settings[key] as never)} /></div></div>;

  return <section className="mx-auto max-w-7xl">
    <header className="mb-8"><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Administration <ChevronRight className="h-3.5 w-3.5" /> Settings</div><h1 className="text-3xl font-bold tracking-tight text-[#00236f]">System settings</h1><p className="mt-2 text-sm text-slate-600">Manage your organization’s preferences, security policy, and connected services.</p></header>
    <div className="grid gap-7 lg:grid-cols-[250px_minmax(0,1fr)]">
      <nav aria-label="Settings sections" className="flex gap-2 overflow-x-auto pb-1 lg:flex-col lg:overflow-visible">{tabs.map(({ id, label, icon: Icon }) => <button className={`flex min-w-max items-center gap-3 rounded-lg px-4 py-3 text-left text-sm font-semibold transition ${tab === id ? "bg-[#1e3a8a] text-[#dce1ff] shadow-sm" : "text-slate-600 hover:bg-slate-200/70 hover:text-slate-900"}`} key={id} onClick={() => setTab(id)} type="button"><Icon className="h-4.5 w-4.5" />{label}</button>)}<div className="mt-3 hidden rounded-lg border border-slate-200 bg-white p-4 lg:block"><p className="text-xs font-semibold text-slate-700">ALMS Enterprise</p><p className="mt-1 text-xs leading-5 text-slate-500">Version 4.2.0 · Stable channel</p></div></nav>
      <div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7">
        {tab === "general" && <div className="space-y-7"><div><h2 className="text-xl font-semibold text-[#00236f]">General settings</h2><p className="mt-1 text-sm text-slate-500">Set the defaults used across your asset management workspace.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Organization name"><input className={inputClass} value={settings.organization} onChange={(e) => update("organization", e.target.value)} /></Field><Field label="Default currency"><select className={inputClass} value={settings.currency} onChange={(e) => update("currency", e.target.value)}><option>NGN (₦)</option><option>USD ($)</option><option>GBP (£)</option><option>EUR (€)</option></select></Field><Field label="Timezone"><select className={inputClass} value={settings.timezone} onChange={(e) => update("timezone", e.target.value)}><option>(UTC+01:00) West Central Africa</option><option>(UTC+00:00) UTC</option><option>(UTC-05:00) Eastern Time</option></select></Field><Field label="Date format"><select className={inputClass} value={settings.dateFormat} onChange={(e) => update("dateFormat", e.target.value)}><option>DD/MM/YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></Field></div><div className="rounded-lg border border-[#dce1ff] bg-[#f7f8ff] p-4"><div className="flex gap-3"><SlidersHorizontal className="mt-0.5 h-5 w-5 shrink-0 text-[#1e3a8a]" /><div><p className="text-sm font-semibold text-slate-800">Workspace defaults</p><p className="mt-1 text-sm leading-5 text-slate-600">Changes apply to new records and reporting views. Existing asset data remains unchanged.</p></div></div></div></div>}
        {tab === "notifications" && <div className="space-y-7"><div><h2 className="text-xl font-semibold text-[#00236f]">Notification preferences</h2><p className="mt-1 text-sm text-slate-500">Choose which operational updates are delivered to administrators.</p></div><div className="space-y-3">{notification("Email notifications", "Receive important activity and summary updates in your inbox.", "emailNotifications")}{notification("System alerts", "Show urgent issues and access warnings as soon as they occur.", "systemAlerts")}{notification("Maintenance reminders", "Send reminders before scheduled service dates and when work becomes overdue.", "maintenanceReminders")}{notification("Weekly asset reports", "Send a scheduled summary of asset lifecycle status every Monday.", "weeklyReports")}{notification("New document shared", "Notify administrators when documents are added to tracked assets.", "documentAlerts")}</div></div>}
        {tab === "security" && <div className="space-y-7"><div><h2 className="text-xl font-semibold text-[#00236f]">Security & access</h2><p className="mt-1 text-sm text-slate-500">Enforce organization-wide security controls and session policies.</p></div><div className="rounded-lg border border-slate-200 bg-slate-50 p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#dce1ff] text-[#00236f]"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-sm font-semibold text-slate-900">Two-factor authentication</p><p className="mt-1 text-sm text-slate-500">Require an additional verification step for administrator accounts.</p></div></div><Toggle checked={settings.twoFactor} onChange={() => update("twoFactor", !settings.twoFactor)} /></div></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Minimum password length"><select className={inputClass} value={settings.passwordLength} onChange={(e) => update("passwordLength", e.target.value)}><option>8 Characters</option><option>12 Characters</option><option>16 Characters</option></select></Field><Field label="Auto-logout delay (minutes)"><input className={inputClass} min="5" type="number" value={settings.autoLogout} onChange={(e) => update("autoLogout", e.target.value)} /></Field></div><div className="grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><p className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Require numbers and symbols</p><p className="flex items-center gap-2"><Check className="h-4 w-4 text-emerald-600" /> Require mixed case passwords</p></div></div>}
        {tab === "integrations" && <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-xl font-semibold text-[#00236f]">Integrations</h2><p className="mt-1 text-sm text-slate-500">Connect ALMS to your identity, finance, and communication tools.</p></div><button className="inline-flex h-10 items-center justify-center gap-2 rounded-md border border-[#1e3a8a] px-4 text-sm font-semibold text-[#1e3a8a] hover:bg-[#f5f7ff]" type="button"><KeyRound className="h-4 w-4" />Generate key</button></div><div className="space-y-3">{[["Azure Active Directory", "Single sign-on & user synchronization", "Connected", Building2], ["Slack alerts", "Real-time alert channels", "Connected", BellRing], ["AWS S3 Storage", "Document and backup archival", "Connected", Cloud], ["SAP ERP Connector", "Financial & inventory mapping", "Disconnected", RefreshCw]].map(([name, description, status, Icon]) => <div className="flex items-center gap-4 rounded-lg border border-slate-200 p-4" key={name as string}><span className="grid h-10 w-10 place-items-center rounded-md border border-slate-200 bg-slate-50 text-[#1e3a8a]">{typeof Icon !== "string" && <Icon className="h-5 w-5" />}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">{name as string}</p><p className="truncate text-xs text-slate-500">{description as string}</p></div><span className={`hidden rounded-full px-2.5 py-1 text-xs font-semibold sm:inline ${status === "Connected" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{status as string}</span><button className="rounded-md border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-700 hover:bg-slate-50" type="button">Manage</button></div>)}</div><button className="inline-flex items-center gap-2 text-sm font-semibold text-[#1e3a8a] hover:text-[#00236f]" type="button"><Plus className="h-4 w-4" />Add an integration</button></div>}
        <footer className="mt-9 flex flex-col-reverse gap-3 border-t border-slate-200 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-slate-500">Changes are saved locally for this browser.</p><button className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-[#1e3a8a] px-5 text-sm font-semibold text-white transition hover:bg-[#00236f]" onClick={save} type="button">{saved && <Check className="h-4 w-4" />}{saved ? "Changes saved" : "Save changes"}</button></footer>
      </div>
    </div>
  </section>;
}
